version: '3'

services:
  app:
    restart: always
    container_name: infobot-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - IN_DOCKER=true
    ports:
      - '3002:3002'
    networks:
      - app_net
    depends_on:
      - db
    volumes:
      - app:/app/files

  db:
    restart: always
    image: postgres:15.2
    container_name: infobot-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: infobot
      POSTGRES_USER: infobot
      POSTGRES_PASSWORD: infobot
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_net

  pgadmin:
    restart: always
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - 80
    ports:
      - 5433:80

  grafana:
    restart: always
    image: grafana/grafana:9.3.6
    container_name: infobot-grafana
    ports:
      - 3001:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  app:
  db:
  grafana:
