version: '3'

services:
  infobot-app:
    restart: always
    container_name: infobot-app
    build:
      context: .
      dockerfile: .docker/Dockerfile-dev
    command: "npm run start:debug"
    volumes:
      - './src:/app/src'
      - ./volumes/app/temp:/app/temp
    environment:
      IN_DOCKER: true
    ports:
      - '3002:3002'
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
