version: '3'

services:
  app:
    restart: always
    container_name: infobot-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      IN_DOCKER: true
    ports:
      - '3002:3002'
    networks:
      - app_net
    depends_on:
      - postgres
    volumes:
      - ./volumes/app/files:/app/files


  postgres:
    image: postgres:15.2
    restart: always
    container_name: infobot-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: infobot
      POSTGRES_USER: infobot
      POSTGRES_PASSWORD: infobot
    volumes:
      - ./volumes/postgres/entrypoint:/docker-entrypoint-initdb.d
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - app_net
  grafana:
    image: grafana/grafana:9.3.6
    container_name: infobot-grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - app_net
    user: ":"

networks:
  app_net:
    driver: bridge