{
 "title": "App database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as value from users"
    }
   ]
  },
  {
   "title": "Total wallets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as value from wallets"
    }
   ]
  },
  {
   "title": "actions",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(actionKey) (rate(bot_action_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}